name: Integration Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: docker.pkg.github.com/zhilyaev/werf-dind@master
        with:
          name: docker.pkg.github.com/zhilyaev/werf-dind
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
